frontend/package-lock.json, frontend/package.json, frontend/public/index.html
=> fix: update missing/extra elements after rebase with master

frontend/src/data/static-pages.js
Closes https://github.com/code4romania/ce-ma-fac/issues/154
Open links in new tab in order not to loose the current page
=> Open links in new tab in order not to loose the current page

frontend/src/data/static-pages.js
Closes #155 
As stated in the issue comment I left the fix consists in adding links with `tel:` and `mailto:` schemes.
=> Direct call & sending email enhancement

frontend/src/components/ContentPage/index.js
=> #112-show related pages at bottom of current page

frontend/src/components/Form/Form.scss, frontend/src/components/Form/results.js, frontend/src/data/static-pages.js
Closes #163 
Missed some phone numbers in my previous pull request for #155. Fixed now.
=> Direct call enhancement - more phone numbers 

frontend/src/components/ContentPage/index.js, frontend/src/components/Home/index.js, frontend/src/utils/instruments.utils.js
Closes #159  => smooth scroll to content when clicking internal links
=> 159 autoscroll to content from quick nav

frontend/package-lock.json, frontend/package.json
=> switch to most recent components version

frontend/package-lock.json, frontend/package.json, frontend/src/App.js
Closes #100 
Updates taskforce-frontend=components to 1.0.7
Adds BackToTop to all pages
=> Feature/100/back to top/tg

frontend/package-lock.json, frontend/package.json, frontend/src/components/Home/index.js, frontend/src/components/Home/styles.scss, frontend/src/components/SearchResults/index.js, frontend/src/components/SearchResults/styles.scss
=> Add support for searching

frontend/src/App.js, frontend/src/components/Home/index.js, frontend/src/data/static-pages.js
=> updated menu and content pages order

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/App.scss
=> fix visual issue header on mobile

frontend/src/App.scss, frontend/src/components/ContentPage/index.js
- Fix logo size
- Define page content slug optional
=> Fix logo size

frontend/src/App.js, frontend/src/components/Footer/index.js, frontend/src/components/PrivacyPolicy.js, frontend/src/components/TermsAndConditions.js
=> Add term and condition page. Add privacy and policy page

frontend/src/data/useful-apps.js
=> add link to rohelp

frontend/src/components/About/index.js, frontend/src/data/useful-apps.js, frontend/src/utils/instruments.utils.js
Closes https://github.com/code4romania/ce-ma-fac/issues/193
=> added diasporahub in sidebar

frontend/package-lock.json, frontend/package.json, frontend/src/App.js
=> update components version and fix for #192

frontend/src/components/Home/styles.scss, frontend/src/data/static-pages.js
=> Update content - add new content pages

frontend/src/App.js, frontend/src/data/static-pages.js
removed banner and small content cleanups
=> Content updates

frontend/package-lock.json, frontend/package.json
closes https://github.com/code4romania/ce-ma-fac/issues/204
updated components version to the one with accessibility updates :smile:
=> updated components version

frontend/package-lock.json, frontend/package.json, frontend/src/components/Home/index.js, frontend/src/data/static-pages.js
Closes https://github.com/code4romania/ce-ma-fac/issues/221
- Highlight 'Model declarație pe proprie răspundere` side menu item
=> Add highlight support for SidebarMenuItem

frontend/src/components/Conduita/index.js, frontend/src/components/Conduita/styles.scss
=> added videos to conduita page

frontend/package.json, frontend/src/App.scss
Remove Bulma dependency because it's already loaded from taskforce-fe-components
=> Remove Bulma

src/components/Conduita/index.js
=> added two new videos to conduita page

.github/workflows/deploy.yml
=> Fixed deploy action

src/components/Home/index.js, src/data/static-pages.js
=> added new page for elections

src/data/static-pages.js
=> updated q&a content

src/data/static-pages.js
=> added new declarations page

src/data/static-pages.js
=> add one more paragraph

src/data/static-pages.js
=> Feature/vaccination updates (#261)

src/data/static-pages.js
=> Update content all site
